### ISSUE TITLE
User settings window hangs 

### ISSUE THREAD

**Issue by Gyzes** [sighupio/permission-manager#94]
k8s: v1.22.2
permission-manager: v1.7.1-rc1

Error process:
1. Create a user and give rights to namespace
2. Remove namespace
3. Open the user for editing
4. The endless process of "... loading" and the out of memory error

![image](https://user-images.githubusercontent.com/90443642/141926847-69ee46de-c7e0-4402-b4bc-5ed3b544e942.png)

Found error correction process:
1. Remove CustomResourceDefinitions
2. Create user again

**Comment by ralgozino** [comment]
Hi @Gyzes !
Thanks for reporting this issue. I can replicate the bug. The frontend hangs, backend seems to be OK though.

**Comment by amoravek** [comment]
The same here. It seems all versions starting from 1.5.0 are affected.

**Comment by bandikoot** [comment]
I might add some clarity — the issue is caused when there's a change in naming pattern of `permissionmanagerusers.permissionmanager.users` resources:
- older versions (up to 1.6.0) create `permissionmanager.user.<username>` — [check out here](https://github.com/sighupio/permission-manager/blob/v1.6.0/internal/resources/user.go#L80)
- latest versions create `permissionmanagerusers.permissionmanager.user.<username>` — this is set by `ResourcePrefix` [variable here](https://github.com/sighupio/permission-manager/blob/a154bc929ba9d9a02de5e874f143a791649d5c2b/internal/resources/v1alpha1_permissionmanageruser.go#L54), [variable itselft is defined here](https://github.com/sighupio/permission-manager/blob/a154bc929ba9d9a02de5e874f143a791649d5c2b/internal/crd/v1alpha1/permissionmanageruser_types.go#L7)

So when, e.g., one
- deploys an older version of PM
- creates users
- upgrades the version of PM
- deletes a previously created user,

this user's page becomes inaccessible.

**Comment by bandikoot** [comment]
The workaround is to manually rename all `permissionmanagerusers.permissionmanager.users` resources to a pattern, suitable for the current **permission-manager** version.

**Comment by luigibarbato** [comment]
First of all, thank you for the issue and especially for waiting. We are back with active permission-manager development. I will take charge of the issue, maybe if we can release the fix for `v1.8.0`. Good catch ✌🏽
